files:
  - source: /global_packs/required_resources/vm-language/assets/dawncraft-quest/lang/en_us.json
    translation: '%original_path%/zh_cn.json'
  - source: /global_packs/required_data/
    translation: '%original_path%/%original_file_name%'
  - source: /global_packs/required_resources/vm-language/assets/
    ignore:
      - dawncraft-quest
      - ob
      - netherskeletons/book
    translation: '%original_path%/zh_cn.json'
